"""Re-constructed the payement's table

Revision ID: ee57554e059a
Revises: d4f1d72095fd
Create Date: 2026-02-12 10:17:01.413015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57554e059a'
down_revision = 'd4f1d72095fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apartment_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_payments_mpesa_receipt_number'), ['mpesa_receipt_number'])
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('late_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_payments_mpesa_receipt_number'), type_='unique')
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('apartment_number')
        batch_op.drop_column('tenant_name')

    # ### end Alembic commands ###
